### PR TITLE
Update to ember@3.4.8

### PR DESCRIPTION
**Pull request by ondrejsevcik**
- I've used [ember-cli-update](https://github.com/ember-cli/ember-cli-update) for most of the stuff
- The target version is latest LTS (3.4.8 at the moment)
- bunch of cli warnings are gone 
- added `/docs` folder into `.eslintignore`
- updated `.travis.yml` config

### CODE REVIEW

**Comment by ondrejsevcik** [comment]
The build has failed when linting `docs` folder. I guess that one should be excluded from eslint as it contains builded output, right?

**Comment by MattCheely** [comment]
Looks like some of the tests are failing?

**Comment by ondrejsevcik** [comment]
Yeah, there was misconfiguration in travis config. It should be fixed now.

**Comment by ondrejsevcik** [comment]
Hi, any update on this one?

**Comment by MattCheely** [comment]
Dang! This totally fell off of my radar. Sorry about that!

**Pull request merged**
